-- SHAZ Gaming public comments table
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 60),
  comment text not null check (char_length(comment) between 2 and 1000),
  created_at timestamptz not null default now()
);

alter table public.comments enable row level security;

drop policy if exists "Anyone can read comments" on public.comments;
create policy "Anyone can read comments"
on public.comments for select
to anon, authenticated
using (true);

drop policy if exists "Anyone can post comments" on public.comments;
create policy "Anyone can post comments"
on public.comments for insert
to anon, authenticated
with check (
  char_length(name) between 2 and 60
  and char_length(comment) between 2 and 1000
);

create index if not exists comments_created_at_idx on public.comments(created_at desc);
